// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pd/state.proto

package dpospb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DposRoot struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Proposer             []byte   `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty"`
	DynastyRoot          []byte   `protobuf:"bytes,3,opt,name=dynasty_root,json=dynastyRoot,proto3" json:"dynasty_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DposRoot) Reset()         { *m = DposRoot{} }
func (m *DposRoot) String() string { return proto.CompactTextString(m) }
func (*DposRoot) ProtoMessage()    {}
func (*DposRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_866e23e4c206859b, []int{0}
}
func (m *DposRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DposRoot.Unmarshal(m, b)
}
func (m *DposRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DposRoot.Marshal(b, m, deterministic)
}
func (dst *DposRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DposRoot.Merge(dst, src)
}
func (m *DposRoot) XXX_Size() int {
	return xxx_messageInfo_DposRoot.Size(m)
}
func (m *DposRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_DposRoot.DiscardUnknown(m)
}

var xxx_messageInfo_DposRoot proto.InternalMessageInfo

func (m *DposRoot) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DposRoot) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *DposRoot) GetDynastyRoot() []byte {
	if m != nil {
		return m.DynastyRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*DposRoot)(nil), "dpospb.DposRoot")
}

func init() { proto.RegisterFile("pd/state.proto", fileDescriptor_state_866e23e4c206859b) }

var fileDescriptor_state_866e23e4c206859b = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x48, 0xd1, 0x2f,
	0x2e, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0x29, 0xc8, 0x2f,
	0x2e, 0x48, 0x52, 0x4a, 0xe7, 0xe2, 0x70, 0x29, 0xc8, 0x2f, 0x0e, 0xca, 0xcf, 0x2f, 0x11, 0x92,
	0xe1, 0xe2, 0x2c, 0xc9, 0xcc, 0x4d, 0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0x90, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0e, 0x42, 0x08, 0x08, 0x49, 0x71, 0x71, 0x14, 0x14, 0xe5, 0x17, 0xe4, 0x17, 0xa7, 0x16,
	0x49, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x04, 0xc1, 0xf9, 0x42, 0x8a, 0x5c, 0x3c, 0x29, 0x95, 0x79,
	0x89, 0xc5, 0x25, 0x95, 0xf1, 0x45, 0xf9, 0xf9, 0x25, 0x12, 0xcc, 0x60, 0x79, 0x6e, 0xa8, 0x18,
	0xc8, 0xf0, 0x24, 0x36, 0xb0, 0xbd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xce, 0x0b,
	0xd8, 0x89, 0x00, 0x00, 0x00,
}
